version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=phenix
      - MYSQL_PASSWORD=password 
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=phenix
      - WORDPRESS_DB_PASSWORD=password 
    volumes:
      - wpdata:/var/www/html

volumes:
  dbdata:
  wpdata: