global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
    - targets: ["10.1.149.19:8081"]

  - job_name: "Orders Container"
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.10.10:9090"]


  - job_name: "Products Container"
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.10.10:8080"]


  - job_name: "Customers Container"
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.10.10:7070"]