version: '3.8'
volumes:
  prometheus_data: {}
services:


  node-exporter:

    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - vagrant_wordpress_network

  cadvisor:

    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8081:8080
    networks:
      - vagrant_wordpress_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - vagrant_wordpress_network

networks:
  vagrant_wordpress_network:
    external: true
