version: '3.8'  


services: 
  node-exporter: 
    image: prom/node-exporter:latest 
    restart: unless-stopped 
    volumes: 
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - monitoring 

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    ports: 
      - 8081:8080 
    networks: 
      - monitoring 
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 

  redis: 
    image: redis:latest 
    ports: 
      - 6379:6379 
    networks: 
      - monitoring

volumes:
  prometheus_data:
    name: prometheus_data

networks:
  monitoring:
    driver: overlay

