version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: "1000"
    ports:
      - 5555:8080
    networks:
      - jenkins-network 
    volumes:
      - jenkinsvol1:/var/jenkins_home
    deploy:
      replicas: 1 

  node-exporter: 
    image: prom/node-exporter:latest 
    user: "1000"
    volumes: 
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - jenkins-network
    deploy:
      replicas: 1

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest
    user: "1000" 
    ports: 
      - 8081:8080 
    networks: 
      - jenkins-network
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    deploy:
      replicas: 1

volumes:
  jenkinsvol1:

networks:
  jenkins-network:
    external: true