version: '3.8'

services:


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - production-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: phenix
      MYSQL_PASSWORD: password
    deploy:
      replicas: 1

  wordpress:
    image: wordpress:latest
    ports:
      - 8888:80
    networks:
      - production-network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=phenix
      - WORDPRESS_DB_PASSWORD=password
    deploy:
      replicas: 1


  node-exporter: 
    image: prom/node-exporter:latest 
    user: "1000"
    volumes: 
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - production-network
    deploy:
      replicas: 1

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest
    user: "1000" 
    ports: 
      - 8081:8080 
    networks: 
      - production-network
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    deploy:
      replicas: 1

volumes:
  db_data:
  wordpress_data:


networks:
  production-network:
    external: true