version: '3.8'

services:


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - production-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: phenix
      MYSQL_PASSWORD: password
    deploy:
      replicas: 1

  wordpress:
    image: wordpress:latest
    ports:
      - 8888:80
    networks:
      - production-network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=phenix
      - WORDPRESS_DB_PASSWORD=password
    deploy:
      replicas: 1

volumes:
  db_data:
  wordpress_data:


networks:
  production-network:
    external: true