version: '3'
services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - 8001:8001