version: '3.8'
services:

  consumer:
    build:
      context: ./customers
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 7070:7070
    restart: always
    container_name: Consumer_Container
    image: consumer_image:${GIT_COMMIT}
    networks:
      - production-network
  
  product:
    build:
      context: ./products
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    networks:
      - production-network
    secrets:
      - mysql_database_user
      - mysql_database_password
      - mysql_database_db
      - api_url
      - consumer_key
      - consumer_secret
      - secret_key
      - name

  order:
    build:
      context: ./orders
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 9090:9090
    restart: always
    container_name: Order_Container
    image: order_image:${GIT_COMMIT}
    networks:
      - production-network

secrets:
  mysql_database_user:
    file: ./secrets.env
    name: MYSQL_DATABASE_USER
  mysql_database_password:
    file: ./secrets.env
    name: MYSQL_DATABASE_PASSWORD
  mysql_database_db:
    file: ./secrets.env
    name: MYSQL_DATABASE_DB
  api_url:
    file: ./secrets.env
    name: API_URL
  consumer_key:
    file: ./secrets.env
    name: CONSUMER_KEY
  consumer_secret:
    file: ./secrets.env
    name: CONSUMER_SECRET
  secret_key:
    file: ./secrets.env
    name: SECRET_KEY
  name:
    file: ./secrets.env
    name: NAME
    
networks:
  production-network:
    external: true