version: '3.1'

services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network
    env_file:
      - ./product/secrets.env

networks:
  vagrant_wordpress_network:
    driver: bridge
