version: '3'
services:

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 7070:7070
    restart: always
    container_name: Consumer_Container
    image: consumer_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 9090:9090
    restart: always
    container_name: Order_Container
    image: order_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network

networks:
  vagrant_wordpress_network:
    external: true