version: '3'
services:

  consumer:
    build:
      context: ./customers
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 7070:7070
    image: consumer_image:${GIT_COMMIT}
    networks:
      - microservice

  product:
    build:
      context: ./products
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 8080:8080
    image: product_image:${GIT_COMMIT}
    networks:
      - microservice

  order:
    build:
      context: ./orders
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 9090:9090
    image: order_image:${GIT_COMMIT}
    networks:
      - microservice

networks:
  microservice:
    external: true