version: '3.1'
services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network
    secrets:
      - mysql_database_user
      - mysql_database_password
      - mysql_database_db
      - mysql_database_host
      - secret_key
      - api_url
      - consumer_key
      - consumer_secret
secrets:
  mysql_database_user:
    file: ./secrets/mysql_database_user.txt
  mysql_database_password:
    file: ./secrets/mysql_database_password.txt
  mysql_database_db:
    file: ./secrets/mysql_database_db.txt
  mysql_database_host:
    file: ./secrets/mysql_database_host.txt
  secret_key:
    file: ./secrets/secret_key.txt
  api_url:
    file: ./secrets/api_url.txt
  consumer_key:
    file: ./secrets/consumer_key.txt
  consumer_secret:
    file: ./secrets/consumer_secret.txt

networks:
  vagrant_wordpress_network:
    driver: bridge
