version: '3'
services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    restart: always