version: '3.8'
services:

  consumer:
    build:
      context: ./customers
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    env_file: ./customers/.env
    ports:
      - 7070:7070
    restart: always
    container_name: Consumer_Container
    image: consumer_image:${GIT_COMMIT}
    networks:
      - production-network
  
  product:
    build:
      context: ./products
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    env_file: ./products/.env
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    networks:
      - production-network

  order:
    build:
      context: ./orders
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    env_file: ./orders/.env
    ports:
      - 9090:9090
    restart: always
    container_name: Order_Container
    image: order_image:${GIT_COMMIT}
    networks:
      - production-network

  webgui:
    build:
      context: ./gui_tests/gui
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 5000:5000
    restart: always
    container_name: Gui_Container
    image: webgui_image:${GIT_COMMIT}
    networks:
      - production-network

  tests:
    build:
      context: ./gui_tests
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    restart: "no"
    container_name: testgui_container
    image: test_image:${GIT_COMMIT}
    networks:
      - production-network

networks:
  production-network:
    external: true