version: '3'
services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    depends_on:
      - db

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 9090:9090
    restart: always
    container_name: Order_Container
    image: order_image:${GIT_COMMIT}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: MySQL_Container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: