version: '3'
services:
  product:
    build:
      context: ./product
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    
    environment:
      DB_HOST: ${MYSQL_DATABASE_HOST}
      DB_NAME: ${MYSQL_DATABASE_DB}
      DB_USER: ${MYSQL_DATABASE_USER}
      DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    
    ports:
      - 8080:8080
    restart: always
    container_name: Product_Container
    image: product_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: $$(git --git-dir=/home/vagrant/agent/ProjectB/.git rev-parse --short HEAD)
    ports:
      - 9090:9090
    restart: always
    container_name: Order_Container
    image: order_image:${GIT_COMMIT}
    networks:
      - vagrant_wordpress_network

networks:
  vagrant_wordpress_network:
    external: true